/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeEContratosRouteImport } from './routes/privacidade-e-contratos'
import { Route as PrestadoresRouteImport } from './routes/prestadores'
import { Route as ObrasRealizadasRouteImport } from './routes/obras-realizadas'
import { Route as DuvidasFrequentesRouteImport } from './routes/duvidas-frequentes'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasRealizadasIndexRouteImport } from './routes/obras-realizadas.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BidsIndexRouteImport } from './routes/bids.index'
import { Route as ObrasRealizadasSlugRouteImport } from './routes/obras-realizadas.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BidsSlugRouteImport } from './routes/bids.$slug'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeEContratosRoute = PrivacidadeEContratosRouteImport.update({
  id: '/privacidade-e-contratos',
  path: '/privacidade-e-contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadoresRoute = PrestadoresRouteImport.update({
  id: '/prestadores',
  path: '/prestadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRealizadasRoute = ObrasRealizadasRouteImport.update({
  id: '/obras-realizadas',
  path: '/obras-realizadas',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasFrequentesRoute = DuvidasFrequentesRouteImport.update({
  id: '/duvidas-frequentes',
  path: '/duvidas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRealizadasIndexRoute = ObrasRealizadasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObrasRealizadasRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BidsIndexRoute = BidsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BidsRoute,
} as any)
const ObrasRealizadasSlugRoute = ObrasRealizadasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ObrasRealizadasRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BidsSlugRoute = BidsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BidsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bids': typeof BidsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/obras-realizadas': typeof ObrasRealizadasRouteWithChildren
  '/prestadores': typeof PrestadoresRoute
  '/privacidade-e-contratos': typeof PrivacidadeEContratosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/bids/$slug': typeof BidsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/obras-realizadas/$slug': typeof ObrasRealizadasSlugRoute
  '/bids/': typeof BidsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/obras-realizadas/': typeof ObrasRealizadasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/prestadores': typeof PrestadoresRoute
  '/privacidade-e-contratos': typeof PrivacidadeEContratosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/bids/$slug': typeof BidsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/obras-realizadas/$slug': typeof ObrasRealizadasSlugRoute
  '/bids': typeof BidsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/obras-realizadas': typeof ObrasRealizadasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bids': typeof BidsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/duvidas-frequentes': typeof DuvidasFrequentesRoute
  '/obras-realizadas': typeof ObrasRealizadasRouteWithChildren
  '/prestadores': typeof PrestadoresRoute
  '/privacidade-e-contratos': typeof PrivacidadeEContratosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/bids/$slug': typeof BidsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/obras-realizadas/$slug': typeof ObrasRealizadasSlugRoute
  '/bids/': typeof BidsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/obras-realizadas/': typeof ObrasRealizadasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bids'
    | '/blog'
    | '/como-funciona'
    | '/duvidas-frequentes'
    | '/obras-realizadas'
    | '/prestadores'
    | '/privacidade-e-contratos'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/bids/$slug'
    | '/blog/$slug'
    | '/obras-realizadas/$slug'
    | '/bids/'
    | '/blog/'
    | '/obras-realizadas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/duvidas-frequentes'
    | '/prestadores'
    | '/privacidade-e-contratos'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/bids/$slug'
    | '/blog/$slug'
    | '/obras-realizadas/$slug'
    | '/bids'
    | '/blog'
    | '/obras-realizadas'
  id:
    | '__root__'
    | '/'
    | '/bids'
    | '/blog'
    | '/como-funciona'
    | '/duvidas-frequentes'
    | '/obras-realizadas'
    | '/prestadores'
    | '/privacidade-e-contratos'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/bids/$slug'
    | '/blog/$slug'
    | '/obras-realizadas/$slug'
    | '/bids/'
    | '/blog/'
    | '/obras-realizadas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidsRoute: typeof BidsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  DuvidasFrequentesRoute: typeof DuvidasFrequentesRoute
  ObrasRealizadasRoute: typeof ObrasRealizadasRouteWithChildren
  PrestadoresRoute: typeof PrestadoresRoute
  PrivacidadeEContratosRoute: typeof PrivacidadeEContratosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade-e-contratos': {
      id: '/privacidade-e-contratos'
      path: '/privacidade-e-contratos'
      fullPath: '/privacidade-e-contratos'
      preLoaderRoute: typeof PrivacidadeEContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestadores': {
      id: '/prestadores'
      path: '/prestadores'
      fullPath: '/prestadores'
      preLoaderRoute: typeof PrestadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras-realizadas': {
      id: '/obras-realizadas'
      path: '/obras-realizadas'
      fullPath: '/obras-realizadas'
      preLoaderRoute: typeof ObrasRealizadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas-frequentes': {
      id: '/duvidas-frequentes'
      path: '/duvidas-frequentes'
      fullPath: '/duvidas-frequentes'
      preLoaderRoute: typeof DuvidasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras-realizadas/': {
      id: '/obras-realizadas/'
      path: '/'
      fullPath: '/obras-realizadas/'
      preLoaderRoute: typeof ObrasRealizadasIndexRouteImport
      parentRoute: typeof ObrasRealizadasRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bids/': {
      id: '/bids/'
      path: '/'
      fullPath: '/bids/'
      preLoaderRoute: typeof BidsIndexRouteImport
      parentRoute: typeof BidsRoute
    }
    '/obras-realizadas/$slug': {
      id: '/obras-realizadas/$slug'
      path: '/$slug'
      fullPath: '/obras-realizadas/$slug'
      preLoaderRoute: typeof ObrasRealizadasSlugRouteImport
      parentRoute: typeof ObrasRealizadasRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bids/$slug': {
      id: '/bids/$slug'
      path: '/$slug'
      fullPath: '/bids/$slug'
      preLoaderRoute: typeof BidsSlugRouteImport
      parentRoute: typeof BidsRoute
    }
  }
}

interface BidsRouteChildren {
  BidsSlugRoute: typeof BidsSlugRoute
  BidsIndexRoute: typeof BidsIndexRoute
}

const BidsRouteChildren: BidsRouteChildren = {
  BidsSlugRoute: BidsSlugRoute,
  BidsIndexRoute: BidsIndexRoute,
}

const BidsRouteWithChildren = BidsRoute._addFileChildren(BidsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ObrasRealizadasRouteChildren {
  ObrasRealizadasSlugRoute: typeof ObrasRealizadasSlugRoute
  ObrasRealizadasIndexRoute: typeof ObrasRealizadasIndexRoute
}

const ObrasRealizadasRouteChildren: ObrasRealizadasRouteChildren = {
  ObrasRealizadasSlugRoute: ObrasRealizadasSlugRoute,
  ObrasRealizadasIndexRoute: ObrasRealizadasIndexRoute,
}

const ObrasRealizadasRouteWithChildren = ObrasRealizadasRoute._addFileChildren(
  ObrasRealizadasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidsRoute: BidsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  DuvidasFrequentesRoute: DuvidasFrequentesRoute,
  ObrasRealizadasRoute: ObrasRealizadasRouteWithChildren,
  PrestadoresRoute: PrestadoresRoute,
  PrivacidadeEContratosRoute: PrivacidadeEContratosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
